[package]
name = "ios-fonts-configurator"
version = "0.1.0"
edition = "2021"
authors = ["Erning"]
description = "A command-line tool to generate .mobileconfig files for iOS font installation"

[dependencies]
clap = { version = "4.5.43", features = ["derive"] }

base64 = "0.21"
anyhow = "1.0"
